# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f194d7ed5c534df5c0908bd3dcd04e1d9650e433c859af4badd3daa2e23d7df857c31f06118fdf662167ccb5a97a076f0431b95fecbecc5f6bdbd2fb037a843

test:
  secret_key_base: a270bf4889a98f30b2d3953ed06b6d7ea56267268b71d018d51365e022bcffdac5ad15726d4cfb1aa628f347c166e980d99d2a01444b9e1aa88380bca1073a43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
